services:

  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
      - /home/toor/traefik/config.yaml:/etc/traefik/traefik.yaml
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.domain.com`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: admin:passwordhash

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.domain.com`)
      traefik.http.routers.blog.tls: true
      traefik.http.routers.blog.tls.certresolver: letsencrypt

networks:
  proxy:
    name: proxy
    external: true

volumes:
  letsencrypt:
    name: letsencrypt
