api:
  dashboard: true
  debug: true

providers:
  docker:
    watch: true
    network: proxy
    exposedByDefault: false

log:
  level: INFO
  filePath: /var/log/traefik/info.log
accessLog:
  filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    asDefault: true
    http:
      tls:
        certresolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: dev@emilesabatier.com
      storage: /letsencrypt/acme.json
      tlschallenge: true
